# Modify this file to suit your environment, and remove ".template" from its name.

# Values formatted like "_env:ENV_VAR_NAME:default_value" can be overridden by the specified environment variable.
# See https://github.com/yesodweb/yesod/wiki/Configuration#overriding-configuration-values-with-environment-variables

static-dir:     "_env:STATIC_DIR:static"
host:           "_env:HOST:*4" # any IPv4 host
port:           "_env:PORT:3000"
approot:        "_env:APPROOT:###:3000" # replace ### with the url of the server, e.g. http://192.168.1.100
ip-from-header: "_env:IP_FROM_HEADER:false"

# Optional values with the following production defaults.
# In development, they default to the inverse.
#
# development: false
# detailed-logging: false
# should-log-all: false
# reload-templates: false
# mutable-static: false
# skip-combining: false

database:
  user:        "###"
  password:    "###"
  host:        "###" # Again, server name or IP address will work, e.g. 192.168.1.100
  database:    "###"
  connections: 10

copyright: not used
#analytics: UA-YOURCODE
